apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cithit/gentrywh:latest
        command: ["/bin/sh", "-c", "cp /index.html /style.css /usr/share/nginx/html/ && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.229.176
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
